services:
  mariadb:
    build: ./requirements/mariadb
    container_name: mariadb
    env_file:
      - .env
    secrets:
      - db_password
      - db_root_password
    volumes:
      mariadb_data:/var/lib/mysql
    networks:
      - inception
volumes:
networks:
secrets:

